"""
analysis_common - UI widgets and metadata shared by the three analysis dialogs

Based on doc/solver_capability/README.md sections 5/6 and realworld_ui_design.md:
  - quantity type table (15 kinds, all available in realworld/probe; voxel uses
    the same quantities but has no energy spectrum)
  - 5 filter types (order-bound: a filter row follows its target quantity)
  - histogram targets are limited to quantities that "support fill1D" (10 kinds)
  - theming: dialogs define no hard-coded colors, they all consume the QSS
    generated by DIALOG_STYLE(dark)
"""

from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton,
    QLineEdit, QComboBox, QDoubleSpinBox, QSpinBox, QCheckBox,
    QFrame, QScrollArea,
)
from PyQt6.QtCore import Qt, pyqtSignal

# -- Quantity type metadata --
# (key, display name, quantity unit, histogram x-axis unit or
#  None = no energy spectrum support)
QUANTITY_TYPES = [
    ("energyDeposit", "energyDeposit", "MeV", "MeV"),
    ("doseDeposit", "doseDeposit", "Gy", "Gy"),
    ("volumeFlux", "volumeFlux", "", "MeV"),
    ("nOfStep", "nOfStep", "", "mm"),
    ("nOfTrack", "nOfTrack", "", "MeV"),
    ("nOfSecondary", "nOfSecondary", "", "MeV"),
    ("cellFlux", "cellFlux", "cm⁻²", "MeV"),
    ("passageCellFlux", "passageCellFlux", "cm⁻²", "MeV"),
    ("passageCellCurrent", "passageCellCurrent", "", "MeV"),
    ("passageTrackLength", "passageTrackLength", "mm", "mm"),
    ("trackLength", "trackLength", "mm", None),
    ("cellCharge", "cellCharge", "e⁺", None),
    ("nOfCollision", "nOfCollision", "", None),
    ("nOfTerminatedTrack", "nOfTerminatedTrack", "", None),
    ("population", "population", "", None),
]

# filter types (Geant4 implements only these 5)
FILTER_TYPES = [
    ("particle", "Particle type"),
    ("kineticEnergy", "Kinetic energy range"),
    ("particleWithEnergy", "Particle + kinetic energy"),
    ("charged", "Charged particles"),
    ("neutral", "Neutral particles"),
]

PARTICLE_CHOICES = [
    "gamma", "e-", "e+", "proton", "neutron",
    "alpha", "He3", "deuteron", "triton",
    "mu-", "mu+", "pi-", "pi+",
]

ENERGY_UNITS = ["MeV", "keV", "GeV"]

MATERIAL_CHOICES = [
    "none", "G4_WATER", "G4_AIR", "G4_Al", "G4_Cu", "G4_Fe", "G4_Pb",
]


def quantity_meta(qtype: str):
    for key, _label, unit, hx_unit in QUANTITY_TYPES:
        if key == qtype:
            return unit, hx_unit
    return "", None


def supports_histogram(qtype: str) -> bool:
    return quantity_meta(qtype)[1] is not None


def gen_quantity_name(existing: list) -> str:
    n = len(existing) + 1
    while f"q{n}" in existing:
        n += 1
    return f"q{n}"


# -- Theme QSS (same tokens as the main window, consumed by all dialogs) --

def DIALOG_STYLE(dark: bool) -> str:
    if dark:
        return """
        QDialog { background-color: #1e1e2e; }
        QLabel { color: #cdd6f4; font-size: 12px; }
        QGroupBox { color: #cdd6f4; font-weight: bold;
            border: 1px solid #45475a; border-radius: 6px;
            margin-top: 12px; padding: 12px 8px 8px 8px; }
        QGroupBox::title { subcontrol-origin: margin; padding: 2px 8px; color: #89b4fa; }
        QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox {
            background-color: #313244; color: #cdd6f4;
            border: 1px solid #45475a; border-radius: 4px;
            padding: 3px 6px; font-size: 12px; }
        QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QDoubleSpinBox:focus {
            border: 1px solid #89b4fa; }
        QCheckBox { color: #cdd6f4; font-size: 12px; }
        QPushButton { background-color: #313244; color: #cdd6f4;
            border: 1px solid #45475a; border-radius: 6px;
            padding: 6px 16px; font-size: 12px; }
        QPushButton:hover { background-color: #45475a; border: 1px solid #89b4fa; }
        QListWidget, QTreeWidget { background-color: #181825; color: #cdd6f4;
            border: 1px solid #45475a; border-radius: 4px; font-size: 12px; }
        QListWidget::item:selected, QTreeWidget::item:selected { background-color: #45475a; }
        QTreeWidget::item:hover { background-color: #282840; }
        QScrollArea { border: none; }
        QScrollBar:vertical { background-color: #1e1e2e; width: 8px; }
        QScrollBar::handle:vertical { background-color: #45475a; border-radius: 4px; }
        """
    return """
        QDialog { background-color: #f5f5f5; }
        QLabel { color: #2c2c2c; font-size: 12px; }
        QGroupBox { color: #2c2c2c; font-weight: bold;
            border: 1px solid #d0d0d0; border-radius: 6px;
            margin-top: 12px; padding: 12px 8px 8px 8px; }
        QGroupBox::title { subcontrol-origin: margin; padding: 2px 8px; color: #0078d4; }
        QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox {
            background-color: #ffffff; color: #2c2c2c;
            border: 1px solid #d0d0d0; border-radius: 4px;
            padding: 3px 6px; font-size: 12px; }
        QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QDoubleSpinBox:focus {
            border: 1px solid #0078d4; }
        QCheckBox { color: #2c2c2c; font-size: 12px; }
        QPushButton { background-color: #f0f0f0; color: #2c2c2c;
            border: 1px solid #d0d0d0; border-radius: 6px;
            padding: 6px 16px; font-size: 12px; }
        QPushButton:hover { background-color: #e4e7eb; border: 1px solid #0078d4; }
        QListWidget, QTreeWidget { background-color: #ffffff; color: #2c2c2c;
            border: 1px solid #d0d0d0; border-radius: 4px; font-size: 12px; }
        QListWidget::item:selected, QTreeWidget::item:selected { background-color: #d0e4f6; color: #1a1a1a; }
        QTreeWidget::item:hover { background-color: #eef3fb; }
        QScrollArea { border: none; }
        QScrollBar:vertical { background-color: #f0f0f0; width: 8px; }
        QScrollBar::handle:vertical { background-color: #c0c0c0; border-radius: 4px; }
        """


# -- Filter editor (expands inline in a single row) --

class FilterEditor(QWidget):
    """Filter editor: one row for the type, one row for the parameters
    (particle / energy range).

    The two-row layout keeps the widgets from overflowing horizontally in a
    narrow panel (parameter boxes running outside the window).
    None when no filter is set.
    """

    changed = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._build_ui()

    def _build_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(4)

        # Row 1: type
        row1 = QHBoxLayout()
        row1.setSpacing(6)
        row1.addWidget(QLabel("Filter:"))
        self._type_cb = QComboBox()
        self._type_cb.addItem("None", None)
        for key, label in FILTER_TYPES:
            self._type_cb.addItem(label, key)
        self._type_cb.currentIndexChanged.connect(self._on_type_changed)
        row1.addWidget(self._type_cb, 1)
        layout.addLayout(row1)

        # Row 2: parameters (particle / kinetic energy range)
        self._param_widget = QWidget()
        pw = QHBoxLayout(self._param_widget)
        pw.setContentsMargins(0, 0, 0, 0)
        pw.setSpacing(6)
        pw.addSpacing(44)  # align with the "Filter:" label in row 1
        self._particle_cb = QComboBox()
        self._particle_cb.addItems(PARTICLE_CHOICES)
        self._particle_cb.setMinimumWidth(110)
        pw.addWidget(self._particle_cb)
        self._min_spin = QDoubleSpinBox()
        self._min_spin.setRange(0.000001, 1e6)
        self._min_spin.setDecimals(4)
        self._min_spin.setValue(0.1)
        self._min_spin.setFixedWidth(95)
        pw.addWidget(self._min_spin)
        pw.addWidget(QLabel("–"))
        self._max_spin = QDoubleSpinBox()
        self._max_spin.setRange(0.000001, 1e6)
        self._max_spin.setDecimals(4)
        self._max_spin.setValue(100.0)
        self._max_spin.setFixedWidth(95)
        pw.addWidget(self._max_spin)
        self._unit_cb = QComboBox()
        self._unit_cb.addItems(ENERGY_UNITS)
        self._unit_cb.setFixedWidth(64)
        pw.addWidget(self._unit_cb)
        pw.addStretch()
        layout.addWidget(self._param_widget)

        self._particle_cb.currentIndexChanged.connect(self.changed.emit)
        self._min_spin.valueChanged.connect(self.changed.emit)
        self._max_spin.valueChanged.connect(self.changed.emit)
        self._unit_cb.currentIndexChanged.connect(self.changed.emit)
        self._on_type_changed()

    def _on_type_changed(self):
        t = self._type_cb.currentData()
        self._param_widget.setVisible(t is not None)
        self._particle_cb.setVisible(t in ("particle", "particleWithEnergy"))
        has_energy = t in ("kineticEnergy", "particleWithEnergy")
        self._min_spin.setVisible(has_energy)
        self._max_spin.setVisible(has_energy)
        self._unit_cb.setVisible(has_energy)
        self.changed.emit()

    def get_filter(self):
        t = self._type_cb.currentData()
        if t is None:
            return None
        if t == "particle":
            return {"t": "particle", "p": self._particle_cb.currentText()}
        if t == "kineticEnergy":
            return {"t": "kineticEnergy",
                    "min": self._min_spin.value(), "max": self._max_spin.value(),
                    "unit": self._unit_cb.currentText()}
        if t == "particleWithEnergy":
            return {"t": "particleWithEnergy", "p": self._particle_cb.currentText(),
                    "min": self._min_spin.value(), "max": self._max_spin.value(),
                    "unit": self._unit_cb.currentText()}
        if t == "charged":
            return {"t": "charged"}
        if t == "neutral":
            return {"t": "neutral"}
        return None

    def set_filter(self, f):
        if not f:
            idx = self._type_cb.findData(None)
            self._type_cb.setCurrentIndex(idx if idx >= 0 else 0)
            return
        t = f.get("t")
        idx = self._type_cb.findData(t)
        if idx >= 0:
            self._type_cb.setCurrentIndex(idx)
        p = f.get("p")
        if p:
            pi = self._particle_cb.findText(p)
            if pi >= 0:
                self._particle_cb.setCurrentIndex(pi)
        if "min" in f:
            self._min_spin.setValue(f["min"])
        if "max" in f:
            self._max_spin.setValue(f["max"])
        if f.get("unit"):
            ui = self._unit_cb.findText(f["unit"])
            if ui >= 0:
                self._unit_cb.setCurrentIndex(ui)


def filter_summary(f) -> str:
    """Short filter description used as the button text on a quantity row."""
    if not f:
        return "+ filter"
    t = f.get("t")
    if t == "particle":
        return f"✓ {f['p']}"
    if t == "kineticEnergy":
        return f"✓ {f['min']}–{f['max']}{f['unit']}"
    if t == "particleWithEnergy":
        return f"✓ {f['p']} {f['min']}–{f['max']}{f['unit']}"
    if t == "charged":
        return "✓ charged"
    if t == "neutral":
        return "✓ neutral"
    return "✓ filter"


# -- Quantity row --

class QuantityRowWidget(QFrame):
    """A single quantity row: name + type + unit (locked) + filter button +
    delete."""

    changed = pyqtSignal()
    removed = pyqtSignal(object)

    def __init__(self, parent=None):
        super().__init__(parent)
        self._filter_editor = None
        self._build_ui()

    def _build_ui(self):
        self.setFrameShape(QFrame.Shape.StyledPanel)
        v = QVBoxLayout(self)
        v.setContentsMargins(8, 6, 8, 6)
        v.setSpacing(4)

        row = QHBoxLayout()
        row.setSpacing(6)

        self._name_edit = QLineEdit()
        self._name_edit.setPlaceholderText("q1")
        self._name_edit.setFixedWidth(90)
        self._name_edit.textChanged.connect(self.changed.emit)
        row.addWidget(self._name_edit)

        self._type_cb = QComboBox()
        for key, _label, _u, _h in QUANTITY_TYPES:
            self._type_cb.addItem(key, key)
        self._type_cb.currentIndexChanged.connect(self._on_type_changed)
        row.addWidget(self._type_cb, 1)

        self._unit_label = QLabel("")
        self._unit_label.setStyleSheet(
            "color: #888888; font-family: Consolas; font-size: 11px;")
        row.addWidget(self._unit_label)

        self._filter_btn = QPushButton("+ filter")
        self._filter_btn.setCheckable(True)
        self._filter_btn.setFixedWidth(120)
        self._filter_btn.toggled.connect(self._on_toggle_filter)
        row.addWidget(self._filter_btn)

        del_btn = QPushButton("✕")
        del_btn.setFixedWidth(28)
        del_btn.setToolTip("Delete this quantity")
        del_btn.clicked.connect(lambda: self.removed.emit(self))
        row.addWidget(del_btn)

        v.addLayout(row)
        self._on_type_changed()

    def _on_type_changed(self):
        qtype = self._type_cb.currentData()
        unit, _hx = quantity_meta(qtype or "energyDeposit")
        self._unit_label.setText(f"[{unit}]" if unit else "[count]")
        self.changed.emit()

    def _on_toggle_filter(self, checked: bool):
        if checked and self._filter_editor is None:
            self._filter_editor = FilterEditor()
            self._filter_editor.changed.connect(self._sync_filter_btn)
            self.layout().addWidget(self._filter_editor)
        if self._filter_editor:
            self._filter_editor.setVisible(checked)
        self._sync_filter_btn()

    def _sync_filter_btn(self):
        f = self._filter_editor.get_filter() if self._filter_editor else None
        self._filter_btn.setText(filter_summary(f))
        self._filter_btn.setChecked(
            self._filter_editor is not None and self._filter_editor.isVisible())
        self.changed.emit()

    def get_quantity(self) -> dict:
        return {
            "name": self._name_edit.text().strip() or "q",
            "type": self._type_cb.currentData() or "energyDeposit",
            "filter": self._filter_editor.get_filter() if self._filter_editor else None,
        }

    def set_quantity(self, q: dict):
        self._name_edit.setText(q.get("name", "q"))
        t = q.get("type", "energyDeposit")
        idx = self._type_cb.findData(t)
        if idx >= 0:
            self._type_cb.setCurrentIndex(idx)
        f = q.get("filter")
        if f:
            if self._filter_editor is None:
                self._filter_editor = FilterEditor()
                self._filter_editor.changed.connect(self._sync_filter_btn)
                self.layout().addWidget(self._filter_editor)
            self._filter_editor.set_filter(f)
            self._filter_editor.setVisible(True)
            self._filter_btn.setChecked(True)
        self._sync_filter_btn()


# -- Quantity list panel --

class QuantityListPanel(QWidget):
    """Scrollable quantity list: add row / inline filter / delete."""

    changed = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._rows = []
        self._build_ui()

    def _build_ui(self):
        v = QVBoxLayout(self)
        v.setContentsMargins(0, 0, 0, 0)
        v.setSpacing(6)

        header = QHBoxLayout()
        header.addWidget(QLabel("Quantity settings"))
        header.addStretch()
        add_btn = QPushButton("➕ Add quantity")
        add_btn.clicked.connect(self.add_row)
        header.addWidget(add_btn)
        v.addLayout(header)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFixedHeight(210)
        scroll.setHorizontalScrollBarPolicy(
            Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self._container = QWidget()
        self._container_layout = QVBoxLayout(self._container)
        self._container_layout.setContentsMargins(0, 0, 0, 0)
        self._container_layout.setSpacing(4)
        self._container_layout.addStretch()
        scroll.setWidget(self._container)
        v.addWidget(scroll)

    def add_row(self, q: dict = None):
        row = QuantityRowWidget()
        if q:
            row.set_quantity(q)
        else:
            names = [r.get_quantity()["name"] for r in self._rows]
            row.set_quantity({"name": gen_quantity_name(names),
                              "type": "energyDeposit", "filter": None})
        row.changed.connect(self.changed.emit)
        row.removed.connect(self._on_row_removed)
        self._rows.append(row)
        # Insert before the stretch item
        self._container_layout.insertWidget(
            self._container_layout.count() - 1, row)
        self.changed.emit()

    def _on_row_removed(self, row):
        if row in self._rows:
            self._rows.remove(row)
        self._container_layout.removeWidget(row)
        row.deleteLater()
        self.changed.emit()

    def get_quantities(self) -> list:
        return [r.get_quantity() for r in self._rows]

    def set_quantities(self, qs: list):
        # Clear
        for r in list(self._rows):
            self._on_row_removed(r)
        for q in qs:
            self.add_row(q)


# -- Histogram row --

class HistogramRowWidget(QFrame):
    """A single energy-spectrum histogram row: target quantity + bins + range
    + log + delete."""

    changed = pyqtSignal()
    removed = pyqtSignal(object)

    def __init__(self, qnames: list, parent=None):
        super().__init__(parent)
        self._qnames = qnames
        self._build_ui()

    def _build_ui(self):
        self.setFrameShape(QFrame.Shape.StyledPanel)
        row = QHBoxLayout(self)
        row.setContentsMargins(8, 5, 8, 5)
        row.setSpacing(6)

        row.addWidget(QLabel("Associated quantity:"))
        self._q_cb = QComboBox()
        self._q_cb.addItems(self._qnames if self._qnames else ["—"])
        self._q_cb.currentIndexChanged.connect(self.changed.emit)
        row.addWidget(self._q_cb, 1)

        row.addWidget(QLabel("bins:"))
        self._bins = QSpinBox()
        self._bins.setRange(2, 10000)
        self._bins.setValue(100)
        self._bins.valueChanged.connect(self.changed.emit)
        row.addWidget(self._bins)

        row.addWidget(QLabel("Range:"))
        self._min = QDoubleSpinBox()
        self._min.setRange(-1e12, 1e12)
        self._min.setDecimals(4)
        self._min.setValue(0.001)
        self._min.valueChanged.connect(self.changed.emit)
        row.addWidget(self._min)
        row.addWidget(QLabel("–"))
        self._max = QDoubleSpinBox()
        self._max.setRange(-1e12, 1e12)
        self._max.setDecimals(4)
        self._max.setValue(1000.0)
        self._max.valueChanged.connect(self.changed.emit)
        row.addWidget(self._max)

        self._log = QCheckBox("log")
        self._log.stateChanged.connect(self.changed.emit)
        row.addWidget(self._log)

        del_btn = QPushButton("✕")
        del_btn.setFixedWidth(28)
        del_btn.clicked.connect(lambda: self.removed.emit(self))
        row.addWidget(del_btn)

    def get_histogram(self) -> dict:
        return {
            "q": self._q_cb.currentText(),
            "bins": self._bins.value(),
            "rng": [self._min.value(), self._max.value()],
            "log": self._log.isChecked(),
        }

    def set_histogram(self, h: dict):
        idx = self._q_cb.findText(h.get("q", ""))
        if idx >= 0:
            self._q_cb.setCurrentIndex(idx)
        self._bins.setValue(h.get("bins", 100))
        rng = h.get("rng", [0.001, 1000.0])
        self._min.setValue(rng[0])
        self._max.setValue(rng[1])
        self._log.setChecked(h.get("log", False))


class HistogramListPanel(QWidget):
    """Energy-spectrum histogram list (probe/realworld only; hidden in
    voxel)."""

    changed = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._rows = []
        self._build_ui()

    def _build_ui(self):
        v = QVBoxLayout(self)
        v.setContentsMargins(0, 0, 0, 0)
        v.setSpacing(6)

        header = QHBoxLayout()
        header.addWidget(QLabel("Energy spectrum histogram"))
        header.addStretch()
        add_btn = QPushButton("➕ Add histogram")
        add_btn.clicked.connect(self.add_row)
        header.addWidget(add_btn)
        v.addLayout(header)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFixedHeight(150)
        scroll.setHorizontalScrollBarPolicy(
            Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self._container = QWidget()
        self._container_layout = QVBoxLayout(self._container)
        self._container_layout.setContentsMargins(0, 0, 0, 0)
        self._container_layout.setSpacing(4)
        self._container_layout.addStretch()
        scroll.setWidget(self._container)
        v.addWidget(scroll)

    def _usable_qnames(self) -> list:
        return self._qnames if hasattr(self, "_qnames") else []

    def set_qnames(self, qnames: list):
        """Candidate target quantities = names of the quantities in the
        current panel that support fill1D.

        Update and emit the signal only when the candidates really change
        (to avoid a changed -> sync -> changed infinite loop).
        """
        if getattr(self, "_qnames", None) == qnames:
            return
        self._qnames = qnames
        for r in self._rows:
            old = r.get_histogram()["q"]
            r._q_cb.clear()
            r._q_cb.addItems(qnames if qnames else ["—"])
            idx = r._q_cb.findText(old)
            if idx >= 0:
                r._q_cb.setCurrentIndex(idx)
        self.changed.emit()

    def add_row(self, h: dict = None):
        names = self._usable_qnames()
        if not names:
            return
        row = HistogramRowWidget(names)
        if h:
            row.set_histogram(h)
        row.changed.connect(self.changed.emit)
        row.removed.connect(self._on_row_removed)
        self._rows.append(row)
        self._container_layout.insertWidget(
            self._container_layout.count() - 1, row)
        self.changed.emit()

    def _on_row_removed(self, row):
        if row in self._rows:
            self._rows.remove(row)
        self._container_layout.removeWidget(row)
        row.deleteLater()
        self.changed.emit()

    def get_histograms(self) -> list:
        return [r.get_histogram() for r in self._rows]

    def set_histograms(self, hs: list):
        for r in list(self._rows):
            self._on_row_removed(r)
        for h in hs:
            self.add_row(h)
