"""
analysis_common - UI widgets and metadata shared by the three analysis dialogs

Based on doc/solver_capability/README.md sections 5/6 and realworld_ui_design.md:
  - quantity type table (15 kinds, all available in realworld/probe; voxel uses
    the same quantities but has no energy spectrum)
  - 5 filter types (order-bound: a filter row follows its target quantity)
  - histogram targets are limited to quantities that "support fill1D" (10 kinds)
  - theming: dialogs define no hard-coded colors, they all consume the QSS
    generated by DIALOG_STYLE(dark)
"""

from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton,
    QLineEdit, QComboBox, QDoubleSpinBox, QSpinBox, QCheckBox,
    QFrame, QScrollArea,
)
from PyQt6.QtCore import Qt, pyqtSignal

# -- Quantity type metadata --
# (key, display name, quantity unit, histogram x-axis unit or
#  None = no energy spectrum support)
QUANTITY_TYPES = [
    ("energyDeposit", "energyDeposit", "MeV", "MeV"),
    ("doseDeposit", "doseDeposit", "Gy", "Gy"),
    ("volumeFlux", "volumeFlux", "", "MeV"),
    ("nOfStep", "nOfStep", "", "mm"),
    ("nOfTrack", "nOfTrack", "", "MeV"),
    ("nOfSecondary", "nOfSecondary", "", "MeV"),
    ("cellFlux", "cellFlux", "cm⁻²", "MeV"),
    ("passageCellFlux", "passageCellFlux", "cm⁻²", "MeV"),
    ("passageCellCurrent", "passageCellCurrent", "", "MeV"),
    ("passageTrackLength", "passageTrackLength", "mm", "mm"),
    ("trackLength", "trackLength", "mm", None),
    ("cellCharge", "cellCharge", "e⁺", None),
    ("nOfCollision", "nOfCollision", "", None),
    ("nOfTerminatedTrack", "nOfTerminatedTrack", "", None),
    ("population", "population", "", None),
]

# filter types (Geant4 implements only these 5)
FILTER_TYPES = [
    ("particle", "Particle type"),
    ("kineticEnergy", "Kinetic energy range"),
    ("particleWithEnergy", "Particle + kinetic energy"),
    ("charged", "Charged particles"),
    ("neutral", "Neutral particles"),
]

PARTICLE_CHOICES = [
    "gamma", "e-", "e+", "proton", "neutron",
    "alpha", "He3", "deuteron", "triton",
    "mu-", "mu+", "pi-", "pi+",
]

ENERGY_UNITS = ["MeV", "keV", "GeV"]

MATERIAL_CHOICES = [
    "none", "G4_WATER", "G4_AIR", "G4_Al", "G4_Cu", "G4_Fe", "G4_Pb",
]


def quantity_meta(qtype: str):
    for key, _label, unit, hx_unit in QUANTITY_TYPES:
        if key == qtype:
            return unit, hx_unit
    return "", None


def supports_histogram(qtype: str) -> bool:
    return quantity_meta(qtype)[1] is not None


def histogram_parameter_conflicts(probes: list) -> list:
    """Detect 1-D histogram settings (bins / range / log) that differ for the
    SAME quantity type across several entries (probes / realworld volumes).

    Overlaying histograms of one quantity type on a single chart only makes
    sense when every series shares the same binning; otherwise the x-axes do
    not align and the comparison is misleading. Dialogs should warn while the
    user still sees the form (visible feedback), not after the run.

    probes: config list entries, each with "qs" (name -> quantity type) and
    "hs" rows {q, bins, rng, log}. Returns human-readable multi-line conflict
    descriptions, one per quantity type, or [] when everything is consistent.
    """
    groups = {}  # quantity type -> [ {probe, qname, bins, rng, log}, ... ]
    for p in probes or []:
        label = str(p.get("name") or p.get("lv") or "?")
        qmeta = {str(q.get("name") or ""): q for q in (p.get("qs") or [])}
        for h in p.get("hs") or []:
            q = qmeta.get(str(h.get("q") or ""))
            if q is None:
                continue
            qtype = str(q.get("type") or "")
            if not qtype:
                continue
            groups.setdefault(qtype, []).append({
                "probe": label,
                "qname": str(h.get("q") or ""),
                "bins": int(h.get("bins", 100)),
                "rng": [round(float(v), 9) for v in h.get("rng", [0, 1])],
                "log": bool(h.get("log", False)),
            })

    out = []
    for qtype, entries in groups.items():
        if len(entries) < 2:  # a lone histogram cannot disagree with anyone
            continue
        base = entries[0]

        def _row(e):
            return (f"{e['probe']}.{e['qname']}  bins={e['bins']}, "
                    f"range=[{e['rng'][0]:g}, {e['rng'][1]:g}], "
                    f"log={'on' if e['log'] else 'off'}")

        diffs = []
        for e in entries[1:]:
            changed = []
            if e["bins"] != base["bins"]:
                changed.append(f"bins {base['bins']} -> {e['bins']}")
            if e["rng"] != base["rng"]:
                changed.append(f"range {base['rng']} -> {e['rng']}")
            if e["log"] != base["log"]:
                changed.append(f"log {'on' if base['log'] else 'off'} "
                               f"-> {'on' if e['log'] else 'off'}")
            if changed:
                diffs.append(f"{e['probe']}.{e['qname']}: "
                             + "; ".join(changed))
        if not diffs:
            continue
        unit = quantity_meta(qtype)[0]
        head = f"{qtype} [{unit}]" if unit else qtype
        lines = [f"{head} - differs from {_row(base)}:", *(_row(e)
                                                           for e in entries)]
        out.append("\n".join(lines))
    return out


def gen_quantity_name(existing: list) -> str:
    n = len(existing) + 1
    while f"q{n}" in existing:
        n += 1
    return f"q{n}"


def fit_size_to_screen(dialog, w: int, h: int,
                       h_margin: int = 80, v_margin: int = 140):
    """Clamp a requested default dialog size to the current screen.

    Windows at >100% display scaling report a smaller usable area in logical
    pixels; a hard-coded default width (e.g. 1150) would then exceed the
    screen and the layout would squeeze the right-hand panel until a
    horizontal scroll bar appears. Returns (w, h) capped to the screen.
    """
    screen = dialog.screen()
    if screen is None:
        from PyQt6.QtGui import QGuiApplication
        screen = QGuiApplication.primaryScreen()
    if screen is None:
        return w, h
    geo = screen.availableGeometry()
    return (min(w, max(640, geo.width() - h_margin)),
            min(h, max(480, geo.height() - v_margin)))


# -- Theme QSS (same tokens as the main window, consumed by all dialogs) --

def DIALOG_STYLE(dark: bool) -> str:
    """Shared modern style for the realworld / probe / voxel dialogs.

    Follows the gdmleditor / cad2gdml look: white(ish) panels, 6px rounded
    inputs with hover + focus accent, a styled combo drop-down button with a
    CSS-triangle arrow and a rounded popup list whose items highlight on
    hover.  Light theme uses the #0078d4 accent; the dark theme mirrors the
    same structure with Catppuccin tokens, so the three dialogs stay visually
    unified in both modes.
    """
    if dark:
        return """
        QDialog { background-color: #1e1e2e; }
        QLabel { color: #cdd6f4; font-size: 12px; background: transparent; }
        QGroupBox { color: #cdd6f4; font-weight: bold;
            border: 1px solid #45475a; border-radius: 8px;
            margin-top: 10px; padding: 14px 10px 10px 10px;
            font-size: 12px; background: transparent; }
        QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left;
            padding: 0 8px; color: #89b4fa; }
        QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox {
            background-color: #313244; color: #cdd6f4;
            border: 1px solid #45475a; border-radius: 6px;
            padding: 4px 10px; font-size: 12px; min-height: 20px;
            selection-background-color: #89b4fa; selection-color: #1e1e2e; }
        QComboBox { padding: 4px 26px 4px 10px; }
        QLineEdit:hover, QComboBox:hover, QSpinBox:hover, QDoubleSpinBox:hover {
            border: 1px solid #89b4fa; }
        QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QDoubleSpinBox:focus {
            border: 1px solid #89b4fa; background-color: #2a2b3d; }
        QComboBox:on { border: 1px solid #89b4fa; background-color: #2a2b3d; }
        QComboBox::drop-down { subcontrol-origin: padding;
            subcontrol-position: top right; width: 22px;
            border: none; border-left: 1px solid #45475a;
            border-top-right-radius: 6px; border-bottom-right-radius: 6px; }
        QComboBox:hover::drop-down { border-left: 1px solid #89b4fa; }
        QComboBox::down-arrow { width: 0; height: 0;
            border-left: 5px solid transparent; border-right: 5px solid transparent;
            border-top: 5px solid #a6adc8; margin: 2px; }
        QComboBox QAbstractItemView { background-color: #181825; color: #cdd6f4;
            border: 1px solid #45475a; border-radius: 8px; padding: 4px;
            outline: none; selection-background-color: transparent;
            selection-color: #cdd6f4; }
        QComboBox QAbstractItemView::item { padding: 6px 10px;
            min-height: 22px; border-radius: 4px; }
        QComboBox QAbstractItemView::item:hover { background-color: #313244; }
        QComboBox QAbstractItemView::item:selected {
            background-color: #45475a; color: #ffffff; }
        QRadioButton { color: #cdd6f4; font-size: 12px;
            background: transparent; border: none; spacing: 6px; }
        QCheckBox { color: #cdd6f4; font-size: 12px; background: transparent; spacing: 6px; }
        QFrame#rowCard { background-color: #26263a;
            border: 1px solid #3a3a4e; border-radius: 6px; }
        QPushButton { background-color: #313244; color: #cdd6f4;
            border: 1px solid #45475a; border-radius: 6px;
            padding: 5px 16px; font-size: 12px; }
        QPushButton:hover { background-color: #45475a; border: 1px solid #89b4fa; }
        QPushButton:pressed { background-color: #585b70; }
        QPushButton:disabled { color: #6c7086; background-color: #26263a;
            border: 1px solid #313244; }
        QListWidget, QTreeWidget { background-color: #181825; color: #cdd6f4;
            border: 1px solid #45475a; border-radius: 8px; font-size: 12px;
            outline: none; }
        QListWidget::item { padding: 4px 8px; border-radius: 4px; }
        QListWidget::item:selected, QTreeWidget::item:selected {
            background-color: #45475a; color: #ffffff; }
        QListWidget::item:hover, QTreeWidget::item:hover { background-color: #313244; }
        QHeaderView::section { background-color: #313244; color: #a6adc8;
            border: none; border-bottom: 1px solid #45475a;
            padding: 4px 8px; font-size: 11px; }
        QScrollArea { border: none; background: transparent; }
        QScrollArea > QWidget > QWidget { background: transparent; }
        QScrollBar:vertical { background: transparent; width: 8px; margin: 0; }
        QScrollBar::handle:vertical { background-color: #45475a;
            border-radius: 4px; min-height: 20px; }
        QScrollBar::handle:vertical:hover { background-color: #585b70; }
        QScrollBar:horizontal { background: transparent; height: 8px; margin: 0; }
        QScrollBar::handle:horizontal { background-color: #45475a;
            border-radius: 4px; min-width: 20px; }
        QScrollBar::add-line, QScrollBar::sub-line { width: 0; height: 0; }
        QSplitter::handle { background-color: #313244; }
        QToolTip { background-color: #313244; color: #cdd6f4;
            border: 1px solid #45475a; padding: 4px 8px; }
        """
    return """
        QDialog { background-color: #f5f5f5; }
        QLabel { color: #2c2c2c; font-size: 12px; background: transparent; }
        QGroupBox { color: #2c2c2c; font-weight: bold;
            border: 1px solid #d0d0d0; border-radius: 8px;
            margin-top: 10px; padding: 14px 10px 10px 10px;
            font-size: 12px; background: transparent; }
        QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left;
            padding: 0 8px; color: #0078d4; }
        QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox {
            background-color: #ffffff; color: #2c2c2c;
            border: 1px solid #d0d0d0; border-radius: 6px;
            padding: 4px 10px; font-size: 12px; min-height: 20px;
            selection-background-color: #0078d4; selection-color: #ffffff; }
        QComboBox { padding: 4px 26px 4px 10px; }
        QLineEdit:hover, QComboBox:hover, QSpinBox:hover, QDoubleSpinBox:hover {
            border: 1px solid #0078d4; background-color: #f8f9fa; }
        QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QDoubleSpinBox:focus {
            border: 1px solid #0078d4; background-color: #f0f4ff; }
        QComboBox:on { border: 1px solid #0078d4; background-color: #f0f4ff; }
        QComboBox::drop-down { subcontrol-origin: padding;
            subcontrol-position: top right; width: 22px;
            border: none; border-left: 1px solid #e0e0e0;
            border-top-right-radius: 6px; border-bottom-right-radius: 6px; }
        QComboBox:hover::drop-down { border-left: 1px solid #0078d4; }
        QComboBox::down-arrow { width: 0; height: 0;
            border-left: 5px solid transparent; border-right: 5px solid transparent;
            border-top: 5px solid #666666; margin: 2px; }
        QComboBox QAbstractItemView { background-color: #ffffff; color: #2c2c2c;
            border: 1px solid #d0d0d0; border-radius: 8px; padding: 4px;
            outline: none; selection-background-color: transparent;
            selection-color: #2c2c2c; }
        QComboBox QAbstractItemView::item { padding: 6px 10px;
            min-height: 22px; border-radius: 4px; }
        QComboBox QAbstractItemView::item:hover { background-color: #e8f0fe; }
        QComboBox QAbstractItemView::item:selected {
            background-color: #d2e3fc; color: #1a1a1a; }
        QRadioButton { color: #2c2c2c; font-size: 12px;
            background: transparent; border: none; spacing: 6px; }
        QCheckBox { color: #2c2c2c; font-size: 12px; background: transparent; spacing: 6px; }
        QFrame#rowCard { background-color: #ffffff;
            border: 1px solid #e0e0e0; border-radius: 6px; }
        QPushButton { background-color: #f0f0f0; color: #2c2c2c;
            border: 1px solid #d0d0d0; border-radius: 6px;
            padding: 5px 16px; font-size: 12px; }
        QPushButton:hover { background-color: #e4e7eb; border: 1px solid #0078d4; }
        QPushButton:pressed { background-color: #d2d5d9; }
        QPushButton:disabled { color: #a0a0a0; background-color: #f7f7f7;
            border: 1px solid #e0e0e0; }
        QListWidget, QTreeWidget { background-color: #ffffff; color: #2c2c2c;
            border: 1px solid #d0d0d0; border-radius: 8px; font-size: 12px;
            outline: none; }
        QListWidget::item { padding: 4px 8px; border-radius: 4px; }
        QListWidget::item:selected, QTreeWidget::item:selected {
            background-color: #d2e3fc; color: #1a1a1a; }
        QListWidget::item:hover, QTreeWidget::item:hover { background-color: #eef3fb; }
        QHeaderView::section { background-color: #ececec; color: #666666;
            border: none; border-bottom: 1px solid #d0d0d0;
            padding: 4px 8px; font-size: 11px; }
        QScrollArea { border: none; background: transparent; }
        QScrollArea > QWidget > QWidget { background: transparent; }
        QScrollBar:vertical { background: transparent; width: 8px; margin: 0; }
        QScrollBar::handle:vertical { background-color: #c0c0c0;
            border-radius: 4px; min-height: 20px; }
        QScrollBar::handle:vertical:hover { background-color: #a0a0a0; }
        QScrollBar:horizontal { background: transparent; height: 8px; margin: 0; }
        QScrollBar::handle:horizontal { background-color: #c0c0c0;
            border-radius: 4px; min-width: 20px; }
        QScrollBar::add-line, QScrollBar::sub-line { width: 0; height: 0; }
        QSplitter::handle { background-color: #d0d0d0; }
        QToolTip { background-color: #ffffff; color: #2c2c2c;
            border: 1px solid #d0d0d0; padding: 4px 8px; }
        """


# -- Filter editor (expands inline in a single row) --

class FilterEditor(QWidget):
    """Filter editor: one row for the type, one row for the parameters
    (particle / energy range).

    The two-row layout keeps the widgets from overflowing horizontally in a
    narrow panel (parameter boxes running outside the window).
    None when no filter is set.
    """

    changed = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._build_ui()

    def _build_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(4)

        # Row 1: type
        row1 = QHBoxLayout()
        row1.setSpacing(6)
        row1.addWidget(QLabel("Filter:"))
        self._type_cb = QComboBox()
        self._type_cb.addItem("None", None)
        for key, label in FILTER_TYPES:
            self._type_cb.addItem(label, key)
        self._type_cb.currentIndexChanged.connect(self._on_type_changed)
        row1.addWidget(self._type_cb, 1)
        layout.addLayout(row1)

        # Row 2: parameters (particle / kinetic energy range)
        self._param_widget = QWidget()
        pw = QHBoxLayout(self._param_widget)
        pw.setContentsMargins(0, 0, 0, 0)
        pw.setSpacing(6)
        pw.addSpacing(44)  # align with the "Filter:" label in row 1
        self._particle_cb = QComboBox()
        self._particle_cb.addItems(PARTICLE_CHOICES)
        self._particle_cb.setMinimumWidth(110)
        pw.addWidget(self._particle_cb)
        self._min_spin = QDoubleSpinBox()
        self._min_spin.setRange(0.000001, 1e6)
        self._min_spin.setDecimals(4)
        self._min_spin.setValue(0.1)
        self._min_spin.setFixedWidth(95)
        pw.addWidget(self._min_spin)
        pw.addWidget(QLabel("–"))
        self._max_spin = QDoubleSpinBox()
        self._max_spin.setRange(0.000001, 1e6)
        self._max_spin.setDecimals(4)
        self._max_spin.setValue(100.0)
        self._max_spin.setFixedWidth(95)
        pw.addWidget(self._max_spin)
        self._unit_cb = QComboBox()
        self._unit_cb.addItems(ENERGY_UNITS)
        self._unit_cb.setFixedWidth(64)
        pw.addWidget(self._unit_cb)
        pw.addStretch()
        layout.addWidget(self._param_widget)

        self._particle_cb.currentIndexChanged.connect(self.changed.emit)
        self._min_spin.valueChanged.connect(self.changed.emit)
        self._max_spin.valueChanged.connect(self.changed.emit)
        self._unit_cb.currentIndexChanged.connect(self.changed.emit)
        self._on_type_changed()

    def _on_type_changed(self):
        t = self._type_cb.currentData()
        self._param_widget.setVisible(t is not None)
        self._particle_cb.setVisible(t in ("particle", "particleWithEnergy"))
        has_energy = t in ("kineticEnergy", "particleWithEnergy")
        self._min_spin.setVisible(has_energy)
        self._max_spin.setVisible(has_energy)
        self._unit_cb.setVisible(has_energy)
        self.changed.emit()

    def get_filter(self):
        t = self._type_cb.currentData()
        if t is None:
            return None
        if t == "particle":
            return {"t": "particle", "p": self._particle_cb.currentText()}
        if t == "kineticEnergy":
            return {"t": "kineticEnergy",
                    "min": self._min_spin.value(), "max": self._max_spin.value(),
                    "unit": self._unit_cb.currentText()}
        if t == "particleWithEnergy":
            return {"t": "particleWithEnergy", "p": self._particle_cb.currentText(),
                    "min": self._min_spin.value(), "max": self._max_spin.value(),
                    "unit": self._unit_cb.currentText()}
        if t == "charged":
            return {"t": "charged"}
        if t == "neutral":
            return {"t": "neutral"}
        return None

    def set_filter(self, f):
        if not f:
            idx = self._type_cb.findData(None)
            self._type_cb.setCurrentIndex(idx if idx >= 0 else 0)
            return
        t = f.get("t")
        idx = self._type_cb.findData(t)
        if idx >= 0:
            self._type_cb.setCurrentIndex(idx)
        p = f.get("p")
        if p:
            pi = self._particle_cb.findText(p)
            if pi >= 0:
                self._particle_cb.setCurrentIndex(pi)
        if "min" in f:
            self._min_spin.setValue(f["min"])
        if "max" in f:
            self._max_spin.setValue(f["max"])
        if f.get("unit"):
            ui = self._unit_cb.findText(f["unit"])
            if ui >= 0:
                self._unit_cb.setCurrentIndex(ui)


def filter_summary(f) -> str:
    """Short filter description used as the button text on a quantity row."""
    if not f:
        return "+ filter"
    t = f.get("t")
    if t == "particle":
        return f"✓ {f['p']}"
    if t == "kineticEnergy":
        return f"✓ {f['min']}–{f['max']}{f['unit']}"
    if t == "particleWithEnergy":
        return f"✓ {f['p']} {f['min']}–{f['max']}{f['unit']}"
    if t == "charged":
        return "✓ charged"
    if t == "neutral":
        return "✓ neutral"
    return "✓ filter"


# -- Quantity row --

class QuantityRowWidget(QFrame):
    """A single quantity row: name + type (fixed width) + unit column (fixed)
    + particle filter dropdown + delete."""

    changed = pyqtSignal()
    removed = pyqtSignal(object)

    def __init__(self, parent=None):
        super().__init__(parent)
        self._build_ui()

    def _build_ui(self):
        self.setFrameShape(QFrame.Shape.StyledPanel)
        # Themed "card": DIALOG_STYLE paints QFrame#rowCard with theme tokens
        # (both light/dark), so these rows never fall back to the default
        # (light) palette in dark mode.
        self.setObjectName("rowCard")
        v = QVBoxLayout(self)
        v.setContentsMargins(8, 6, 8, 6)
        v.setSpacing(4)

        row = QHBoxLayout()
        row.setSpacing(6)

        self._name_edit = QLineEdit()
        self._name_edit.setPlaceholderText("q1")
        self._name_edit.setFixedWidth(110)
        self._name_edit.textChanged.connect(self.changed.emit)
        row.addWidget(self._name_edit)

        self._type_cb = QComboBox()
        for key, _label, _u, _h in QUANTITY_TYPES:
            self._type_cb.addItem(key, key)
        # Fixed width: the dropdown no longer stretches across the row, so the
        # unit column stays at a stable position.
        self._type_cb.setFixedWidth(180)
        self._type_cb.currentIndexChanged.connect(self._on_type_changed)
        row.addWidget(self._type_cb)

        # Fixed-width unit column: aligned and never shifts when the type
        # (and therefore the unit text) changes.
        self._unit_label = QLabel("")
        # No explicit colour: inherit the dialog theme's text colour, so the
        # unit stays readable in both light and dark mode.
        self._unit_label.setStyleSheet(
            "font-family: Consolas; font-size: 11px;")
        self._unit_label.setFixedWidth(64)
        self._unit_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        row.addWidget(self._unit_label)

        # Particle filter as a single dropdown ("no filter" by default)
        self._filter_cb = QComboBox()
        self._filter_cb.addItem("no filter", None)
        for p in PARTICLE_CHOICES:
            self._filter_cb.addItem(p, p)
        self._filter_cb.setFixedWidth(120)
        self._filter_cb.currentIndexChanged.connect(self.changed.emit)
        row.addWidget(self._filter_cb)

        # Remaining space goes before the delete button, so the ✕ sits at the
        # right edge - aligned with the histogram rows' delete buttons.
        row.addStretch()

        del_btn = QPushButton("✕")
        del_btn.setFixedWidth(28)
        del_btn.setToolTip("Delete this quantity")
        del_btn.clicked.connect(lambda: self.removed.emit(self))
        row.addWidget(del_btn)

        v.addLayout(row)
        self._on_type_changed()

    def _on_type_changed(self):
        qtype = self._type_cb.currentData()
        unit, _hx = quantity_meta(qtype or "energyDeposit")
        self._unit_label.setText(f"[{unit}]" if unit else "[count]")
        self.changed.emit()

    def get_quantity(self) -> dict:
        p = self._filter_cb.currentData()
        return {
            "name": self._name_edit.text().strip() or "q",
            "type": self._type_cb.currentData() or "energyDeposit",
            "filter": {"t": "particle", "p": p} if p else None,
        }

    def set_quantity(self, q: dict):
        self._name_edit.setText(q.get("name", "q"))
        t = q.get("type", "energyDeposit")
        idx = self._type_cb.findData(t)
        if idx >= 0:
            self._type_cb.setCurrentIndex(idx)
        f = q.get("filter") or {}
        if f.get("t") == "particle":
            pidx = self._filter_cb.findData(f.get("p"))
            if pidx >= 0:
                self._filter_cb.setCurrentIndex(pidx)
        # Non-particle filters (legacy configs) fall back to "no filter".


# -- Quantity list panel --

class QuantityListPanel(QWidget):
    """Scrollable quantity list: add row / inline filter / delete."""

    changed = pyqtSignal()

    def __init__(self, parent=None, stretchable=False,
                 scroll_min_height=210):
        super().__init__(parent)
        self._rows = []
        self._stretchable = stretchable
        self._scroll_min_height = scroll_min_height
        self._build_ui()

    def _build_ui(self):
        v = QVBoxLayout(self)
        v.setContentsMargins(0, 0, 0, 0)
        v.setSpacing(6)

        header = QHBoxLayout()
        header.addWidget(QLabel("Quantity settings"))
        header.addStretch()
        add_btn = QPushButton("➕ Add quantity")
        add_btn.clicked.connect(self.add_row)
        header.addWidget(add_btn)
        v.addLayout(header)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        if self._stretchable:
            # Elastic height: the dialog layout distributes the extra
            # vertical space between the quantity/histogram areas so the
            # right panel fills the window instead of leaving gaps.
            scroll.setMinimumHeight(self._scroll_min_height)
        else:
            scroll.setFixedHeight(self._scroll_min_height)
        scroll.setHorizontalScrollBarPolicy(
            Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self._container = QWidget()
        self._container_layout = QVBoxLayout(self._container)
        self._container_layout.setContentsMargins(0, 0, 0, 0)
        self._container_layout.setSpacing(4)
        self._container_layout.addStretch()
        scroll.setWidget(self._container)
        v.addWidget(scroll)

    def add_row(self, q: dict = None):
        row = QuantityRowWidget()
        if q:
            row.set_quantity(q)
        else:
            names = [r.get_quantity()["name"] for r in self._rows]
            row.set_quantity({"name": gen_quantity_name(names),
                              "type": "energyDeposit", "filter": None})
        row.changed.connect(self.changed.emit)
        row.removed.connect(self._on_row_removed)
        self._rows.append(row)
        # Insert before the stretch item
        self._container_layout.insertWidget(
            self._container_layout.count() - 1, row)
        self.changed.emit()

    def _on_row_removed(self, row):
        if row in self._rows:
            self._rows.remove(row)
        self._container_layout.removeWidget(row)
        row.deleteLater()
        self.changed.emit()

    def get_quantities(self) -> list:
        return [r.get_quantity() for r in self._rows]

    def set_quantities(self, qs: list):
        # Clear
        for r in list(self._rows):
            self._on_row_removed(r)
        for q in qs:
            self.add_row(q)


# -- Histogram row --

class HistogramRowWidget(QFrame):
    """A single 1D-histogram row: target quantity + bins + range (the range
    unit follows the linked quantity) + log + delete."""

    changed = pyqtSignal()
    removed = pyqtSignal(object)

    def __init__(self, qnames: list, qunits: dict = None, parent=None):
        super().__init__(parent)
        self._qnames = qnames
        self._qunits = qunits or {}
        self._build_ui()

    def _build_ui(self):
        self.setFrameShape(QFrame.Shape.StyledPanel)
        self.setObjectName("rowCard")
        row = QHBoxLayout(self)
        row.setContentsMargins(8, 5, 8, 5)
        # Tight spacing keeps the row narrow enough that no horizontal
        # scroll bar appears in the right-hand panels of the dialogs.
        row.setSpacing(5)

        row.addWidget(QLabel("Quantity:"))
        # The target is typed like the quantity Name box instead of being
        # picked from a dropdown: new histogram rows auto-assign the defined
        # quantities in order (q1, q2, …), and the typed text is validated
        # against the defined quantities (see _refresh_target).
        self._q_edit = QLineEdit()
        self._q_edit.setPlaceholderText("q1")
        self._q_edit.setMinimumWidth(110)
        self._q_edit.textChanged.connect(self._on_q_changed)
        row.addWidget(self._q_edit, 1)

        row.addWidget(QLabel("bins:"))
        self._bins = QSpinBox()
        self._bins.setRange(2, 10000)
        self._bins.setValue(100)
        self._bins.valueChanged.connect(self.changed.emit)
        row.addWidget(self._bins)

        row.addWidget(QLabel("Range:"))
        self._min = QDoubleSpinBox()
        self._min.setRange(-1e12, 1e12)
        self._min.setDecimals(4)
        self._min.setValue(0.001)
        self._min.setFixedWidth(88)
        self._min.valueChanged.connect(self.changed.emit)
        row.addWidget(self._min)
        row.addWidget(QLabel("–"))
        self._max = QDoubleSpinBox()
        self._max.setRange(-1e12, 1e12)
        self._max.setDecimals(4)
        self._max.setValue(1000.0)
        self._max.setFixedWidth(88)
        self._max.valueChanged.connect(self.changed.emit)
        row.addWidget(self._max)

        # Range unit (MeV / mm / ...) follows the selected quantity. No
        # explicit colour: inherits the theme's text colour (light/dark).
        self._unit_label = QLabel("")
        self._unit_label.setStyleSheet(
            "font-family: Consolas; font-size: 11px;")
        self._unit_label.setFixedWidth(40)
        row.addWidget(self._unit_label)

        self._log = QCheckBox("log")
        self._log.stateChanged.connect(self.changed.emit)
        row.addWidget(self._log)

        del_btn = QPushButton("✕")
        del_btn.setFixedWidth(28)
        del_btn.clicked.connect(lambda: self.removed.emit(self))
        row.addWidget(del_btn)

        self._set_choices(self._qnames, self._qunits)

    def _set_choices(self, qnames: list, qunits: dict = None):
        """Refresh the set of DEFINED quantities that validate the typed
        target and resolve its x-axis unit. Never overwrites the text the
        user typed."""
        self._qnames = qnames or []
        self._qunits = qunits or {}
        self._refresh_target()

    def _refresh_target(self):
        """Re-validate the typed quantity name and update the range-unit
        column. A name that matches no defined quantity gets a red outline
        (mac_builder silently drops histogram rows whose target quantity is
        not defined on the same mesh)."""
        name = self.get_qname()
        unit = self._qunits.get(name, "")
        self._unit_label.setText(unit if unit else "")
        ok = (not name) or (name in self._qnames)
        self._q_edit.setStyleSheet(
            "" if ok else "QLineEdit { border: 1px solid #d34f4f; }")
        return ok

    def set_qname(self, name: str):
        """Typed target quantity (textChanged -> _on_q_changed emits changed)."""
        self._q_edit.setText(name or "")

    def get_qname(self) -> str:
        return self._q_edit.text().strip()

    def _on_q_changed(self, *_):
        self._refresh_target()
        self.changed.emit()

    def get_histogram(self) -> dict:
        return {
            "q": self.get_qname(),
            "bins": self._bins.value(),
            "rng": [self._min.value(), self._max.value()],
            "log": self._log.isChecked(),
        }

    def set_histogram(self, h: dict):
        self.set_qname(h.get("q", ""))
        self._bins.setValue(h.get("bins", 100))
        rng = h.get("rng", [0.001, 1000.0])
        self._min.setValue(rng[0])
        self._max.setValue(rng[1])
        self._log.setChecked(h.get("log", False))


class HistogramListPanel(QWidget):
    """Energy-spectrum histogram list (probe/realworld only; hidden in
    voxel)."""

    changed = pyqtSignal()

    def __init__(self, parent=None, stretchable=False,
                 scroll_min_height=150):
        super().__init__(parent)
        self._rows = []
        self._stretchable = stretchable
        self._scroll_min_height = scroll_min_height
        self._build_ui()

    def _build_ui(self):
        v = QVBoxLayout(self)
        v.setContentsMargins(0, 0, 0, 0)
        v.setSpacing(6)

        header = QHBoxLayout()
        header.addWidget(QLabel("1D histogram"))
        header.addStretch()
        add_btn = QPushButton("➕ Add histogram")
        add_btn.clicked.connect(self.add_row)
        header.addWidget(add_btn)
        v.addLayout(header)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        if self._stretchable:
            scroll.setMinimumHeight(self._scroll_min_height)
        else:
            scroll.setFixedHeight(self._scroll_min_height)
        scroll.setHorizontalScrollBarPolicy(
            Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self._container = QWidget()
        self._container_layout = QVBoxLayout(self._container)
        self._container_layout.setContentsMargins(0, 0, 0, 0)
        self._container_layout.setSpacing(4)
        self._container_layout.addStretch()
        scroll.setWidget(self._container)
        v.addWidget(scroll)

    def _usable_qnames(self) -> list:
        return self._qnames if hasattr(self, "_qnames") else []

    def set_qnames(self, qnames: list, units: dict = None):
        """Candidate target quantities = names of the quantities in the
        current panel that support fill1D (units maps name -> range unit).

        Update and emit the signal only when the candidates really change
        (to avoid a changed -> sync -> changed infinite loop).
        """
        if (getattr(self, "_qnames", None) == qnames
                and getattr(self, "_qunits", None) == units):
            return
        self._qnames = qnames
        self._qunits = units or {}
        for r in self._rows:
            # Keeps the typed text, only re-validates it and refreshes the
            # x-axis unit for the current quantity list.
            r._set_choices(qnames, self._qunits)
        self.changed.emit()

    def _next_free_qname(self) -> str:
        """First defined quantity (in definition order) that is not yet the
        target of any histogram row, so consecutive Add clicks map to
        q1, q2, q3, … in lockstep with the quantity list."""
        names = self._usable_qnames()
        if not names:
            return ""
        used = {r.get_histogram().get("q") for r in self._rows}
        for n in names:
            if n not in used:
                return n
        return names[0]

    def add_row(self, h: dict = None):
        names = self._usable_qnames()
        if not names:
            return
        row = HistogramRowWidget(names, getattr(self, "_qunits", {}))
        if h:
            row.set_histogram(h)
        else:
            # Auto-assign the next quantity that has no histogram yet, so the
            # new row lines up with the quantity list instead of always
            # defaulting to the first quantity.
            row.set_histogram({"q": self._next_free_qname()})
        row.changed.connect(self.changed.emit)
        row.removed.connect(self._on_row_removed)
        self._rows.append(row)
        self._container_layout.insertWidget(
            self._container_layout.count() - 1, row)
        self.changed.emit()

    def _on_row_removed(self, row):
        if row in self._rows:
            self._rows.remove(row)
        self._container_layout.removeWidget(row)
        row.deleteLater()
        self.changed.emit()

    def get_histograms(self) -> list:
        return [r.get_histogram() for r in self._rows]

    def set_histograms(self, hs: list):
        for r in list(self._rows):
            self._on_row_removed(r)
        for h in hs:
            self.add_row(h)
